CREATE DATABASE farmdb

CREATE TABLE farmer (
  id SERIAL PRIMARY KEY,
  name VARCHAR(200),
  age INT,
  district VARCHAR(200),
  state VARCHAR(200),
  crop VARCHAR(100),
  reg_date DATE DEFAULT CURRENT DATE
);